server:
  port: 7000
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/goldengeek22/worlddev-config-store
          default-label: master
          timeout: 10 # Time limit to establish a connection with the repository
          clone-on-start: true # Clones the remote repository locally on startup
          force-pull: true # Forces pulling the remote repository and discarding any local changes
